// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebClient.Models;

#nullable disable

namespace WebClient.Migrations
{
    [DbContext(typeof(SkuffrollDbContext))]
    [Migration("20250521161550_FinalModelsInitial")]
    partial class FinalModelsInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebClient.Models.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOriginalContent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("background", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundFeature", b =>
                {
                    b.Property<int>("BackgroundId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("BackgroundId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("background_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundItem", b =>
                {
                    b.Property<int>("BackgroundId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("BackgroundId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("background_items", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundSkill", b =>
                {
                    b.Property<int>("BackgroundId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("BackgroundId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("background_skills", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("campaign", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<string>("ArmorProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("integer");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bonds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Flaws")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<int>("Hp")
                        .HasColumnType("integer");

                    b.Property<string>("Ideals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalityTraits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int?>("SubraceId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("ClassId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SubraceId");

                    b.HasIndex("UserId");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterAbilityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaScore")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ConScore")
                        .HasColumnType("integer");

                    b.Property<int>("DexScore")
                        .HasColumnType("integer");

                    b.Property<int>("IntScore")
                        .HasColumnType("integer");

                    b.Property<int>("StrScore")
                        .HasColumnType("integer");

                    b.Property<int>("WisScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_ability_score", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterFeature", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("character_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterInventory", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("character_inventory", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterSavingThrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cha")
                        .HasColumnType("boolean");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("Con")
                        .HasColumnType("boolean");

                    b.Property<bool>("Dex")
                        .HasColumnType("boolean");

                    b.Property<bool>("int")
                        .HasColumnType("boolean");

                    b.Property<bool>("Str")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wis")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_saving_throws", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acrobatics")
                        .HasColumnType("boolean");

                    b.Property<bool>("AnimalHandling")
                        .HasColumnType("boolean");

                    b.Property<bool>("Arcana")
                        .HasColumnType("boolean");

                    b.Property<bool>("Athletics")
                        .HasColumnType("boolean");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("Deception")
                        .HasColumnType("boolean");

                    b.Property<bool>("History")
                        .HasColumnType("boolean");

                    b.Property<bool>("Insight")
                        .HasColumnType("boolean");

                    b.Property<bool>("Intimidation")
                        .HasColumnType("boolean");

                    b.Property<bool>("Investigation")
                        .HasColumnType("boolean");

                    b.Property<bool>("Medicine")
                        .HasColumnType("boolean");

                    b.Property<bool>("Nature")
                        .HasColumnType("boolean");

                    b.Property<bool>("Perception")
                        .HasColumnType("boolean");

                    b.Property<bool>("Performance")
                        .HasColumnType("boolean");

                    b.Property<bool>("Persuasion")
                        .HasColumnType("boolean");

                    b.Property<bool>("Religion")
                        .HasColumnType("boolean");

                    b.Property<bool>("SleightOfHand")
                        .HasColumnType("boolean");

                    b.Property<bool>("Stealth")
                        .HasColumnType("boolean");

                    b.Property<bool>("Survival")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_skills", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfProficientSkills")
                        .HasColumnType("integer");

                    b.Property<string>("ArmorProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstSavingThrow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOriginalContent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondSavingThrow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartingHp")
                        .HasColumnType("integer");

                    b.Property<string>("ToolProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.ClassSkill", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("ClassId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("class_skills", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("XCoordinate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("YCoordinate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("feature", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.FirstItemSet", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("ClassId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("first_item_set", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("item", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebClient.Models.LevelingTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("EighteenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("EighthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("EleventhTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FifteenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FifthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FourteenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FourthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("NineteenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("NinthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SeventeenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SeventhTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SixteenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SixthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("TenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThirdTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThirteenthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("TwelfthTalentId")
                        .HasColumnType("integer");

                    b.Property<int?>("TwentiethTalentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("EighteenthTalentId");

                    b.HasIndex("EighthTalentId");

                    b.HasIndex("EleventhTalentId");

                    b.HasIndex("FifteenthTalentId");

                    b.HasIndex("FifthTalentId");

                    b.HasIndex("FirstTalentId");

                    b.HasIndex("FourteenthTalentId");

                    b.HasIndex("FourthTalentId");

                    b.HasIndex("NineteenthTalentId");

                    b.HasIndex("NinthTalentId");

                    b.HasIndex("SecondTalentId");

                    b.HasIndex("SeventeenthTalentId");

                    b.HasIndex("SeventhTalentId");

                    b.HasIndex("SixteenthTalentId");

                    b.HasIndex("SixthTalentId");

                    b.HasIndex("TenthTalentId");

                    b.HasIndex("ThirdTalentId");

                    b.HasIndex("ThirteenthTalentId");

                    b.HasIndex("TwelfthTalentId");

                    b.HasIndex("TwentiethTalentId");

                    b.ToTable("leveling_table", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<int?>("HostId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("HostId");

                    b.ToTable("lobby", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.LobbyChat", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("CampaignId", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("lobby_chat", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Location", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.LoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("lore_entry", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.PrivateMessage", b =>
                {
                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("ReceiverId", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("private_messages", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("quest", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.QuestEvent", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "QuestId");

                    b.HasIndex("LocationId");

                    b.HasIndex("QuestId");

                    b.ToTable("quest_event", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("ConIncrease")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DexIncrease")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntIncrease")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOriginalContent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("StrIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("WisIncrease")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("race", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.RaceFeature", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("RaceId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("race_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.SecondItemSet", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("ClassId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("second_item_set", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Squad", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.ToTable("squad", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Subrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChaIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("ConIncrease")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DexIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("IntIncrease")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOriginalContent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("StrIncrease")
                        .HasColumnType("integer");

                    b.Property<int>("WisIncrease")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("subrace", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.SubraceFeature", b =>
                {
                    b.Property<int>("SubraceId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.HasKey("SubraceId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("subrace_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserCampaign", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("user_campaigns", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserCharacter", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("user_characters", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserFriend", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("user_friends", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserInLobby", b =>
                {
                    b.Property<int>("LobbyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LobbyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("users_in_lobby", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.WeaponTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("weapon_tag", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.WeaponTagWeapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponTagId")
                        .HasColumnType("integer");

                    b.HasKey("WeaponId", "WeaponTagId");

                    b.HasIndex("WeaponTagId");

                    b.ToTable("weapon_tag_weapon", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Armor", b =>
                {
                    b.HasBaseType("WebClient.Models.Item");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<bool>("DisadvantageOnStealth")
                        .HasColumnType("boolean");

                    b.Property<int>("StrengthRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("armor", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Weapon", b =>
                {
                    b.HasBaseType("WebClient.Models.Item");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMartial")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("boolean");

                    b.ToTable("weapon", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundFeature", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("BackgroundFeatures")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("BackgroundFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("WebClient.Models.BackgroundItem", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("BackgroundItems")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("BackgroundItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.BackgroundSkill", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("BackgroundSkills")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Skill", "Skill")
                        .WithMany("BackgroundSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("WebClient.Models.Character", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("Characters")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Subrace", "Subrace")
                        .WithMany("Characters")
                        .HasForeignKey("SubraceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Background");

                    b.Navigation("Class");

                    b.Navigation("Race");

                    b.Navigation("Subrace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.CharacterAbilityScore", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("AbilityScores")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WebClient.Models.CharacterFeature", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterFeatures")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("CharacterFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("WebClient.Models.CharacterInventory", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterInventories")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("CharacterInventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.CharacterSavingThrow", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterSavingThrows")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WebClient.Models.CharacterSkill", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WebClient.Models.ClassSkill", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("ClassSkills")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Skill", "Skill")
                        .WithMany("ClassSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("WebClient.Models.Event", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("Events")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("WebClient.Models.FirstItemSet", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("FirstItemSets")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("FirstItemSets")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.LevelingTable", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("LevelingTables")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Feature", "EighteenthTalent")
                        .WithMany()
                        .HasForeignKey("EighteenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "EighthTalent")
                        .WithMany()
                        .HasForeignKey("EighthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "EleventhTalent")
                        .WithMany()
                        .HasForeignKey("EleventhTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FifteenthTalent")
                        .WithMany()
                        .HasForeignKey("FifteenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FifthTalent")
                        .WithMany()
                        .HasForeignKey("FifthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FirstTalent")
                        .WithMany()
                        .HasForeignKey("FirstTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FourteenthTalent")
                        .WithMany()
                        .HasForeignKey("FourteenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FourthTalent")
                        .WithMany()
                        .HasForeignKey("FourthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "NineteenthTalent")
                        .WithMany()
                        .HasForeignKey("NineteenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "NinthTalent")
                        .WithMany()
                        .HasForeignKey("NinthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SecondTalent")
                        .WithMany()
                        .HasForeignKey("SecondTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SeventeenthTalent")
                        .WithMany()
                        .HasForeignKey("SeventeenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SeventhTalent")
                        .WithMany()
                        .HasForeignKey("SeventhTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SixteenthTalent")
                        .WithMany()
                        .HasForeignKey("SixteenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SixthTalent")
                        .WithMany()
                        .HasForeignKey("SixthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "TenthTalent")
                        .WithMany()
                        .HasForeignKey("TenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "ThirdTalent")
                        .WithMany()
                        .HasForeignKey("ThirdTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "ThirteenthTalent")
                        .WithMany()
                        .HasForeignKey("ThirteenthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "TwelfthTalent")
                        .WithMany()
                        .HasForeignKey("TwelfthTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "TwentiethTalent")
                        .WithMany()
                        .HasForeignKey("TwentiethTalentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("EighteenthTalent");

                    b.Navigation("EighthTalent");

                    b.Navigation("EleventhTalent");

                    b.Navigation("FifteenthTalent");

                    b.Navigation("FifthTalent");

                    b.Navigation("FirstTalent");

                    b.Navigation("FourteenthTalent");

                    b.Navigation("FourthTalent");

                    b.Navigation("NineteenthTalent");

                    b.Navigation("NinthTalent");

                    b.Navigation("SecondTalent");

                    b.Navigation("SeventeenthTalent");

                    b.Navigation("SeventhTalent");

                    b.Navigation("SixteenthTalent");

                    b.Navigation("SixthTalent");

                    b.Navigation("TenthTalent");

                    b.Navigation("ThirdTalent");

                    b.Navigation("ThirteenthTalent");

                    b.Navigation("TwelfthTalent");

                    b.Navigation("TwentiethTalent");
                });

            modelBuilder.Entity("WebClient.Models.Lobby", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("Lobbies")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "Host")
                        .WithMany("HostedLobbies")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("WebClient.Models.LobbyChat", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("LobbyChats")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Message", "Message")
                        .WithMany("LobbyChats")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("WebClient.Models.Location", b =>
                {
                    b.HasOne("WebClient.Models.Event", "Event")
                        .WithOne("Location")
                        .HasForeignKey("WebClient.Models.Location", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WebClient.Models.LoreEntry", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("LoreEntries")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("WebClient.Models.Message", b =>
                {
                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.PrivateMessage", b =>
                {
                    b.HasOne("WebClient.Models.Message", "Message")
                        .WithMany("PrivateMessages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "Receiver")
                        .WithMany("PrivateMessagesReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("WebClient.Models.Quest", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("Quests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("WebClient.Models.QuestEvent", b =>
                {
                    b.HasOne("WebClient.Models.Event", "Event")
                        .WithMany("QuestEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Quest", "Quest")
                        .WithMany("QuestEvents")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Location");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("WebClient.Models.RaceFeature", b =>
                {
                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("RaceFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Race", "Race")
                        .WithMany("RaceFeatures")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WebClient.Models.SecondItemSet", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("SecondItemSets")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("SecondItemSets")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.Squad", b =>
                {
                    b.HasOne("WebClient.Models.Event", "Event")
                        .WithOne("Squad")
                        .HasForeignKey("WebClient.Models.Squad", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WebClient.Models.Subrace", b =>
                {
                    b.HasOne("WebClient.Models.Race", "Race")
                        .WithMany("Subraces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WebClient.Models.SubraceFeature", b =>
                {
                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("SubraceFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Subrace", "Subrace")
                        .WithMany("SubraceFeatures")
                        .HasForeignKey("SubraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Subrace");
                });

            modelBuilder.Entity("WebClient.Models.UserCampaign", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("UserCampaigns")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UserCampaigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.UserCharacter", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("UserCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UserCharacters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.UserFriend", b =>
                {
                    b.HasOne("WebClient.Models.User", "Friend")
                        .WithMany("FriendOfUsers")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UserFriends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.UserInLobby", b =>
                {
                    b.HasOne("WebClient.Models.Lobby", "Lobby")
                        .WithMany("UsersInLobby")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UsersInLobby")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.WeaponTagWeapon", b =>
                {
                    b.HasOne("WebClient.Models.Weapon", "Weapon")
                        .WithMany("WeaponTagWeapons")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.WeaponTag", "WeaponTag")
                        .WithMany("WeaponTagWeapons")
                        .HasForeignKey("WeaponTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");

                    b.Navigation("WeaponTag");
                });

            modelBuilder.Entity("WebClient.Models.Armor", b =>
                {
                    b.HasOne("WebClient.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("WebClient.Models.Armor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebClient.Models.Weapon", b =>
                {
                    b.HasOne("WebClient.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("WebClient.Models.Weapon", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebClient.Models.Background", b =>
                {
                    b.Navigation("BackgroundFeatures");

                    b.Navigation("BackgroundItems");

                    b.Navigation("BackgroundSkills");

                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WebClient.Models.Campaign", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Lobbies");

                    b.Navigation("LobbyChats");

                    b.Navigation("LoreEntries");

                    b.Navigation("Quests");

                    b.Navigation("UserCampaigns");
                });

            modelBuilder.Entity("WebClient.Models.Character", b =>
                {
                    b.Navigation("AbilityScores");

                    b.Navigation("CharacterFeatures");

                    b.Navigation("CharacterInventories");

                    b.Navigation("CharacterSavingThrows");

                    b.Navigation("CharacterSkills");

                    b.Navigation("UserCharacters");
                });

            modelBuilder.Entity("WebClient.Models.Class", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ClassSkills");

                    b.Navigation("FirstItemSets");

                    b.Navigation("LevelingTables");

                    b.Navigation("SecondItemSets");
                });

            modelBuilder.Entity("WebClient.Models.Event", b =>
                {
                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("QuestEvents");

                    b.Navigation("Squad")
                        .IsRequired();
                });

            modelBuilder.Entity("WebClient.Models.Feature", b =>
                {
                    b.Navigation("BackgroundFeatures");

                    b.Navigation("CharacterFeatures");

                    b.Navigation("RaceFeatures");

                    b.Navigation("SubraceFeatures");
                });

            modelBuilder.Entity("WebClient.Models.Item", b =>
                {
                    b.Navigation("BackgroundItems");

                    b.Navigation("CharacterInventories");

                    b.Navigation("FirstItemSets");

                    b.Navigation("SecondItemSets");
                });

            modelBuilder.Entity("WebClient.Models.Lobby", b =>
                {
                    b.Navigation("UsersInLobby");
                });

            modelBuilder.Entity("WebClient.Models.Message", b =>
                {
                    b.Navigation("LobbyChats");

                    b.Navigation("PrivateMessages");
                });

            modelBuilder.Entity("WebClient.Models.Quest", b =>
                {
                    b.Navigation("QuestEvents");
                });

            modelBuilder.Entity("WebClient.Models.Race", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("RaceFeatures");

                    b.Navigation("Subraces");
                });

            modelBuilder.Entity("WebClient.Models.Skill", b =>
                {
                    b.Navigation("BackgroundSkills");

                    b.Navigation("ClassSkills");
                });

            modelBuilder.Entity("WebClient.Models.Subrace", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("SubraceFeatures");
                });

            modelBuilder.Entity("WebClient.Models.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("FriendOfUsers");

                    b.Navigation("HostedLobbies");

                    b.Navigation("Messages");

                    b.Navigation("PrivateMessagesReceived");

                    b.Navigation("UserCampaigns");

                    b.Navigation("UserCharacters");

                    b.Navigation("UserFriends");

                    b.Navigation("UsersInLobby");
                });

            modelBuilder.Entity("WebClient.Models.WeaponTag", b =>
                {
                    b.Navigation("WeaponTagWeapons");
                });

            modelBuilder.Entity("WebClient.Models.Weapon", b =>
                {
                    b.Navigation("WeaponTagWeapons");
                });
#pragma warning restore 612, 618
        }
    }
}
