// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebClient.Models;

#nullable disable

namespace WebClient.Migrations
{
    [DbContext(typeof(SkuffrollDbContext))]
    partial class SkuffrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebClient.Models.Background", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_original_content")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tool_proficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("vehicle_proficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("background", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundFeature", b =>
                {
                    b.Property<int>("background_id")
                        .HasColumnType("integer");

                    b.Property<int>("feature_id")
                        .HasColumnType("integer");

                    b.HasKey("background_id", "feature_id");

                    b.HasIndex("feature_id");

                    b.ToTable("background_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundItem", b =>
                {
                    b.Property<int>("background_id")
                        .HasColumnType("integer");

                    b.Property<int>("item_id")
                        .HasColumnType("integer");

                    b.HasKey("background_id", "item_id");

                    b.HasIndex("item_id");

                    b.ToTable("background_items", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundSkill", b =>
                {
                    b.Property<int>("background_id")
                        .HasColumnType("integer");

                    b.Property<int>("skill_id")
                        .HasColumnType("integer");

                    b.HasKey("background_id", "skill_id");

                    b.HasIndex("skill_id");

                    b.ToTable("background_skills", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Campaign", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("campaign", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Character", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.Property<string>("alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("appearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("armor_class")
                        .HasColumnType("integer");

                    b.Property<string>("armor_proficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("background_id")
                        .HasColumnType("integer");

                    b.Property<string>("backstory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bonds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("class_id")
                        .HasColumnType("integer");

                    b.Property<string>("flaws")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("height")
                        .HasColumnType("numeric");

                    b.Property<int>("hp")
                        .HasColumnType("integer");

                    b.Property<string>("ideals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("personality_traits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("race_id")
                        .HasColumnType("integer");

                    b.Property<int>("speed")
                        .HasColumnType("integer");

                    b.Property<int?>("subrace_id")
                        .HasColumnType("integer");

                    b.Property<string>("tool_proficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.Property<string>("vehicle_proficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("weapon_proficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("weight")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("background_id");

                    b.HasIndex("class_id");

                    b.HasIndex("race_id");

                    b.HasIndex("subrace_id");

                    b.HasIndex("user_id");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterAbilityScore", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cha_score")
                        .HasColumnType("integer");

                    b.Property<int>("character_id")
                        .HasColumnType("integer");

                    b.Property<int>("con_score")
                        .HasColumnType("integer");

                    b.Property<int>("dex_score")
                        .HasColumnType("integer");

                    b.Property<int>("int_score")
                        .HasColumnType("integer");

                    b.Property<int>("str_score")
                        .HasColumnType("integer");

                    b.Property<int>("wis_score")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("character_id");

                    b.ToTable("character_ability_score", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterFeature", b =>
                {
                    b.Property<int>("character_id")
                        .HasColumnType("integer");

                    b.Property<int>("feature_id")
                        .HasColumnType("integer");

                    b.HasKey("character_id", "feature_id");

                    b.HasIndex("feature_id");

                    b.ToTable("character_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterInventory", b =>
                {
                    b.Property<int>("character_id")
                        .HasColumnType("integer");

                    b.Property<int>("item_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("character_id", "item_id");

                    b.HasIndex("item_id");

                    b.ToTable("character_inventory", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterSavingThrow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("cha")
                        .HasColumnType("boolean");

                    b.Property<int>("character_id")
                        .HasColumnType("integer");

                    b.Property<bool>("con")
                        .HasColumnType("boolean");

                    b.Property<bool>("dex")
                        .HasColumnType("boolean");

                    b.Property<bool>("int")
                        .HasColumnType("boolean");

                    b.Property<bool>("str")
                        .HasColumnType("boolean");

                    b.Property<bool>("wis")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("character_id");

                    b.ToTable("character_saving_throws", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.CharacterSkill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("acrobatics")
                        .HasColumnType("boolean");

                    b.Property<bool>("animal_handling")
                        .HasColumnType("boolean");

                    b.Property<bool>("arcana")
                        .HasColumnType("boolean");

                    b.Property<bool>("athletics")
                        .HasColumnType("boolean");

                    b.Property<int>("character_id")
                        .HasColumnType("integer");

                    b.Property<bool>("deception")
                        .HasColumnType("boolean");

                    b.Property<bool>("history")
                        .HasColumnType("boolean");

                    b.Property<bool>("insight")
                        .HasColumnType("boolean");

                    b.Property<bool>("intimidation")
                        .HasColumnType("boolean");

                    b.Property<bool>("investigation")
                        .HasColumnType("boolean");

                    b.Property<bool>("medicine")
                        .HasColumnType("boolean");

                    b.Property<bool>("nature")
                        .HasColumnType("boolean");

                    b.Property<bool>("perception")
                        .HasColumnType("boolean");

                    b.Property<bool>("performance")
                        .HasColumnType("boolean");

                    b.Property<bool>("persuasion")
                        .HasColumnType("boolean");

                    b.Property<bool>("religion")
                        .HasColumnType("boolean");

                    b.Property<bool>("sleight_of_hand")
                        .HasColumnType("boolean");

                    b.Property<bool>("stealth")
                        .HasColumnType("boolean");

                    b.Property<bool>("survival")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("character_id");

                    b.ToTable("character_skills", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Class", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("amount_of_proficient_skills")
                        .HasColumnType("integer");

                    b.Property<string>("armor_proficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_saving_throw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_homebrew")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_original_content")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("second_saving_throw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("starting_hp")
                        .HasColumnType("integer");

                    b.Property<string>("tool_proficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("weapon_proficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.ClassSkill", b =>
                {
                    b.Property<int>("class_id")
                        .HasColumnType("integer");

                    b.Property<int>("skill_id")
                        .HasColumnType("integer");

                    b.HasKey("class_id", "skill_id");

                    b.HasIndex("skill_id");

                    b.ToTable("class_skills", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("campaign_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("x_coordinate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("y_coordinate")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("campaign_id");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Feature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("feature", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.FirstItemSet", b =>
                {
                    b.Property<int>("class_id")
                        .HasColumnType("integer");

                    b.Property<int>("item_id")
                        .HasColumnType("integer");

                    b.HasKey("class_id", "item_id");

                    b.HasIndex("item_id");

                    b.ToTable("first_item_set", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("weight")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("item", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebClient.Models.LevelingTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("class_id")
                        .HasColumnType("integer");

                    b.Property<int?>("eighteenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("eighth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("eleventh_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("fifteenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("fifth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("first_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("fourteenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("fourth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("nineteenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("ninth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("second_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("seventeenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("seventh_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("sixteenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("sixth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("tenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("third_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("thirteenth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("twelfth_talent_id")
                        .HasColumnType("integer");

                    b.Property<int?>("twentieth_talent_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("class_id");

                    b.HasIndex("eighteenth_talent_id");

                    b.HasIndex("eighth_talent_id");

                    b.HasIndex("eleventh_talent_id");

                    b.HasIndex("fifteenth_talent_id");

                    b.HasIndex("fifth_talent_id");

                    b.HasIndex("first_talent_id");

                    b.HasIndex("fourteenth_talent_id");

                    b.HasIndex("fourth_talent_id");

                    b.HasIndex("nineteenth_talent_id");

                    b.HasIndex("ninth_talent_id");

                    b.HasIndex("second_talent_id");

                    b.HasIndex("seventeenth_talent_id");

                    b.HasIndex("seventh_talent_id");

                    b.HasIndex("sixteenth_talent_id");

                    b.HasIndex("sixth_talent_id");

                    b.HasIndex("tenth_talent_id");

                    b.HasIndex("third_talent_id");

                    b.HasIndex("thirteenth_talent_id");

                    b.HasIndex("twelfth_talent_id");

                    b.HasIndex("twentieth_talent_id");

                    b.ToTable("leveling_table", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Lobby", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("campaign_id")
                        .HasColumnType("integer");

                    b.Property<int?>("host_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("campaign_id");

                    b.HasIndex("host_id");

                    b.ToTable("lobby", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.LobbyChat", b =>
                {
                    b.Property<int>("campaign_id")
                        .HasColumnType("integer");

                    b.Property<int>("message_id")
                        .HasColumnType("integer");

                    b.HasKey("campaign_id", "message_id");

                    b.HasIndex("message_id");

                    b.ToTable("lobby_chat", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Location", b =>
                {
                    b.Property<int>("event_id")
                        .HasColumnType("integer");

                    b.HasKey("event_id");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.LoreEntry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("campaign_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("campaign_id");

                    b.ToTable("lore_entry", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("message_content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.PrivateMessage", b =>
                {
                    b.Property<int>("receiver_id")
                        .HasColumnType("integer");

                    b.Property<int>("message_id")
                        .HasColumnType("integer");

                    b.HasKey("receiver_id", "message_id");

                    b.HasIndex("message_id");

                    b.ToTable("private_messages", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Quest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("campaign_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("campaign_id");

                    b.ToTable("quest", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.QuestEvent", b =>
                {
                    b.Property<int>("event_id")
                        .HasColumnType("integer");

                    b.Property<int>("quest_id")
                        .HasColumnType("integer");

                    b.Property<int?>("location_id")
                        .HasColumnType("integer");

                    b.HasKey("event_id", "quest_id");

                    b.HasIndex("location_id");

                    b.HasIndex("quest_id");

                    b.ToTable("quest_event", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Race", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cha_increase")
                        .HasColumnType("integer");

                    b.Property<int>("con_increase")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("dex_increase")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("int_increase")
                        .HasColumnType("integer");

                    b.Property<bool>("is_homebrew")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_original_content")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("speed")
                        .HasColumnType("integer");

                    b.Property<int>("str_increase")
                        .HasColumnType("integer");

                    b.Property<int>("wis_increase")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("race", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.RaceFeature", b =>
                {
                    b.Property<int>("race_id")
                        .HasColumnType("integer");

                    b.Property<int>("feature_id")
                        .HasColumnType("integer");

                    b.HasKey("race_id", "feature_id");

                    b.HasIndex("feature_id");

                    b.ToTable("race_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.SecondItemSet", b =>
                {
                    b.Property<int>("class_id")
                        .HasColumnType("integer");

                    b.Property<int>("item_id")
                        .HasColumnType("integer");

                    b.HasKey("class_id", "item_id");

                    b.HasIndex("item_id");

                    b.ToTable("second_item_set", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Squad", b =>
                {
                    b.Property<int>("event_id")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("event_id");

                    b.ToTable("squad", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Subrace", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cha_increase")
                        .HasColumnType("integer");

                    b.Property<int>("con_increase")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("dex_increase")
                        .HasColumnType("integer");

                    b.Property<int>("int_increase")
                        .HasColumnType("integer");

                    b.Property<bool>("is_original_content")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("race_id")
                        .HasColumnType("integer");

                    b.Property<int>("str_increase")
                        .HasColumnType("integer");

                    b.Property<int>("wis_increase")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("race_id");

                    b.ToTable("subrace", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.SubraceFeature", b =>
                {
                    b.Property<int>("subrace_id")
                        .HasColumnType("integer");

                    b.Property<int>("feature_id")
                        .HasColumnType("integer");

                    b.HasKey("subrace_id", "feature_id");

                    b.HasIndex("feature_id");

                    b.ToTable("subrace_features", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("registration_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserCampaign", b =>
                {
                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<int>("campaign_id")
                        .HasColumnType("integer");

                    b.HasKey("user_id", "campaign_id");

                    b.HasIndex("campaign_id");

                    b.ToTable("user_campaigns", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserCharacter", b =>
                {
                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<int>("character_id")
                        .HasColumnType("integer");

                    b.HasKey("user_id", "character_id");

                    b.HasIndex("character_id");

                    b.ToTable("user_characters", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserFriend", b =>
                {
                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<int>("friend_id")
                        .HasColumnType("integer");

                    b.HasKey("user_id", "friend_id");

                    b.HasIndex("friend_id");

                    b.ToTable("user_friends", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.UserInLobby", b =>
                {
                    b.Property<int>("lobby_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("lobby_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("users_in_lobby", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.WeaponTag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("weapon_tag", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.WeaponTagWeapon", b =>
                {
                    b.Property<int>("weapon_id")
                        .HasColumnType("integer");

                    b.Property<int>("weapon_tag_id")
                        .HasColumnType("integer");

                    b.HasKey("weapon_id", "weapon_tag_id");

                    b.HasIndex("weapon_tag_id");

                    b.ToTable("weapon_tag_weapon", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Armor", b =>
                {
                    b.HasBaseType("WebClient.Models.Item");

                    b.Property<int>("armor_class")
                        .HasColumnType("integer");

                    b.Property<bool>("disadvantage_on_stealth")
                        .HasColumnType("boolean");

                    b.Property<int>("strength_requirement")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("armor", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.Weapon", b =>
                {
                    b.HasBaseType("WebClient.Models.Item");

                    b.Property<string>("damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("damage_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_martial")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_ranged")
                        .HasColumnType("boolean");

                    b.ToTable("weapon", (string)null);
                });

            modelBuilder.Entity("WebClient.Models.BackgroundFeature", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("BackgroundFeatures")
                        .HasForeignKey("background_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("BackgroundFeatures")
                        .HasForeignKey("feature_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("WebClient.Models.BackgroundItem", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("BackgroundItems")
                        .HasForeignKey("background_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("BackgroundItems")
                        .HasForeignKey("item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.BackgroundSkill", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("BackgroundSkills")
                        .HasForeignKey("background_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Skill", "Skill")
                        .WithMany("BackgroundSkills")
                        .HasForeignKey("skill_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("WebClient.Models.Character", b =>
                {
                    b.HasOne("WebClient.Models.Background", "Background")
                        .WithMany("Characters")
                        .HasForeignKey("background_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("race_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Subrace", "Subrace")
                        .WithMany("Characters")
                        .HasForeignKey("subrace_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Background");

                    b.Navigation("Class");

                    b.Navigation("Race");

                    b.Navigation("Subrace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.CharacterAbilityScore", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("AbilityScores")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WebClient.Models.CharacterFeature", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterFeatures")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("CharacterFeatures")
                        .HasForeignKey("feature_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("WebClient.Models.CharacterInventory", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterInventories")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("CharacterInventories")
                        .HasForeignKey("item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.CharacterSavingThrow", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterSavingThrows")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WebClient.Models.CharacterSkill", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WebClient.Models.ClassSkill", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("ClassSkills")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Skill", "Skill")
                        .WithMany("ClassSkills")
                        .HasForeignKey("skill_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("WebClient.Models.Event", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("Events")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("WebClient.Models.FirstItemSet", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("FirstItemSets")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("FirstItemSets")
                        .HasForeignKey("item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.LevelingTable", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("LevelingTables")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Feature", "EighteenthTalent")
                        .WithMany()
                        .HasForeignKey("eighteenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "EighthTalent")
                        .WithMany()
                        .HasForeignKey("eighth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "EleventhTalent")
                        .WithMany()
                        .HasForeignKey("eleventh_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FifteenthTalent")
                        .WithMany()
                        .HasForeignKey("fifteenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FifthTalent")
                        .WithMany()
                        .HasForeignKey("fifth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FirstTalent")
                        .WithMany()
                        .HasForeignKey("first_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FourteenthTalent")
                        .WithMany()
                        .HasForeignKey("fourteenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "FourthTalent")
                        .WithMany()
                        .HasForeignKey("fourth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "NineteenthTalent")
                        .WithMany()
                        .HasForeignKey("nineteenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "NinthTalent")
                        .WithMany()
                        .HasForeignKey("ninth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SecondTalent")
                        .WithMany()
                        .HasForeignKey("second_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SeventeenthTalent")
                        .WithMany()
                        .HasForeignKey("seventeenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SeventhTalent")
                        .WithMany()
                        .HasForeignKey("seventh_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SixteenthTalent")
                        .WithMany()
                        .HasForeignKey("sixteenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "SixthTalent")
                        .WithMany()
                        .HasForeignKey("sixth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "TenthTalent")
                        .WithMany()
                        .HasForeignKey("tenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "ThirdTalent")
                        .WithMany()
                        .HasForeignKey("third_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "ThirteenthTalent")
                        .WithMany()
                        .HasForeignKey("thirteenth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "TwelfthTalent")
                        .WithMany()
                        .HasForeignKey("twelfth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Feature", "TwentiethTalent")
                        .WithMany()
                        .HasForeignKey("twentieth_talent_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("EighteenthTalent");

                    b.Navigation("EighthTalent");

                    b.Navigation("EleventhTalent");

                    b.Navigation("FifteenthTalent");

                    b.Navigation("FifthTalent");

                    b.Navigation("FirstTalent");

                    b.Navigation("FourteenthTalent");

                    b.Navigation("FourthTalent");

                    b.Navigation("NineteenthTalent");

                    b.Navigation("NinthTalent");

                    b.Navigation("SecondTalent");

                    b.Navigation("SeventeenthTalent");

                    b.Navigation("SeventhTalent");

                    b.Navigation("SixteenthTalent");

                    b.Navigation("SixthTalent");

                    b.Navigation("TenthTalent");

                    b.Navigation("ThirdTalent");

                    b.Navigation("ThirteenthTalent");

                    b.Navigation("TwelfthTalent");

                    b.Navigation("TwentiethTalent");
                });

            modelBuilder.Entity("WebClient.Models.Lobby", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("Lobbies")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "Host")
                        .WithMany("HostedLobbies")
                        .HasForeignKey("host_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("WebClient.Models.LobbyChat", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("LobbyChats")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Message", "Message")
                        .WithMany("LobbyChats")
                        .HasForeignKey("message_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("WebClient.Models.Location", b =>
                {
                    b.HasOne("WebClient.Models.Event", "Event")
                        .WithOne("Location")
                        .HasForeignKey("WebClient.Models.Location", "event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WebClient.Models.LoreEntry", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("LoreEntries")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("WebClient.Models.Message", b =>
                {
                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.PrivateMessage", b =>
                {
                    b.HasOne("WebClient.Models.Message", "Message")
                        .WithMany("PrivateMessages")
                        .HasForeignKey("message_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "Receiver")
                        .WithMany("PrivateMessagesReceived")
                        .HasForeignKey("receiver_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("WebClient.Models.Quest", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("Quests")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("WebClient.Models.QuestEvent", b =>
                {
                    b.HasOne("WebClient.Models.Event", "Event")
                        .WithMany("QuestEvents")
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebClient.Models.Quest", "Quest")
                        .WithMany("QuestEvents")
                        .HasForeignKey("quest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Location");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("WebClient.Models.RaceFeature", b =>
                {
                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("RaceFeatures")
                        .HasForeignKey("feature_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Race", "Race")
                        .WithMany("RaceFeatures")
                        .HasForeignKey("race_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WebClient.Models.SecondItemSet", b =>
                {
                    b.HasOne("WebClient.Models.Class", "Class")
                        .WithMany("SecondItemSets")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Item", "Item")
                        .WithMany("SecondItemSets")
                        .HasForeignKey("item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebClient.Models.Squad", b =>
                {
                    b.HasOne("WebClient.Models.Event", "Event")
                        .WithOne("Squad")
                        .HasForeignKey("WebClient.Models.Squad", "event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WebClient.Models.Subrace", b =>
                {
                    b.HasOne("WebClient.Models.Race", "Race")
                        .WithMany("Subraces")
                        .HasForeignKey("race_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WebClient.Models.SubraceFeature", b =>
                {
                    b.HasOne("WebClient.Models.Feature", "Feature")
                        .WithMany("SubraceFeatures")
                        .HasForeignKey("feature_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.Subrace", "Subrace")
                        .WithMany("SubraceFeatures")
                        .HasForeignKey("subrace_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Subrace");
                });

            modelBuilder.Entity("WebClient.Models.UserCampaign", b =>
                {
                    b.HasOne("WebClient.Models.Campaign", "Campaign")
                        .WithMany("UserCampaigns")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UserCampaigns")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.UserCharacter", b =>
                {
                    b.HasOne("WebClient.Models.Character", "Character")
                        .WithMany("UserCharacters")
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UserCharacters")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.UserFriend", b =>
                {
                    b.HasOne("WebClient.Models.User", "Friend")
                        .WithMany("FriendOfUsers")
                        .HasForeignKey("friend_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UserFriends")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.UserInLobby", b =>
                {
                    b.HasOne("WebClient.Models.Lobby", "Lobby")
                        .WithMany("UsersInLobby")
                        .HasForeignKey("lobby_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.User", "User")
                        .WithMany("UsersInLobby")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebClient.Models.WeaponTagWeapon", b =>
                {
                    b.HasOne("WebClient.Models.Weapon", "Weapon")
                        .WithMany("WeaponTagWeapons")
                        .HasForeignKey("weapon_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebClient.Models.WeaponTag", "WeaponTag")
                        .WithMany("WeaponTagWeapons")
                        .HasForeignKey("weapon_tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");

                    b.Navigation("WeaponTag");
                });

            modelBuilder.Entity("WebClient.Models.Armor", b =>
                {
                    b.HasOne("WebClient.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("WebClient.Models.Armor", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebClient.Models.Weapon", b =>
                {
                    b.HasOne("WebClient.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("WebClient.Models.Weapon", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebClient.Models.Background", b =>
                {
                    b.Navigation("BackgroundFeatures");

                    b.Navigation("BackgroundItems");

                    b.Navigation("BackgroundSkills");

                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WebClient.Models.Campaign", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Lobbies");

                    b.Navigation("LobbyChats");

                    b.Navigation("LoreEntries");

                    b.Navigation("Quests");

                    b.Navigation("UserCampaigns");
                });

            modelBuilder.Entity("WebClient.Models.Character", b =>
                {
                    b.Navigation("AbilityScores");

                    b.Navigation("CharacterFeatures");

                    b.Navigation("CharacterInventories");

                    b.Navigation("CharacterSavingThrows");

                    b.Navigation("CharacterSkills");

                    b.Navigation("UserCharacters");
                });

            modelBuilder.Entity("WebClient.Models.Class", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ClassSkills");

                    b.Navigation("FirstItemSets");

                    b.Navigation("LevelingTables");

                    b.Navigation("SecondItemSets");
                });

            modelBuilder.Entity("WebClient.Models.Event", b =>
                {
                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("QuestEvents");

                    b.Navigation("Squad")
                        .IsRequired();
                });

            modelBuilder.Entity("WebClient.Models.Feature", b =>
                {
                    b.Navigation("BackgroundFeatures");

                    b.Navigation("CharacterFeatures");

                    b.Navigation("RaceFeatures");

                    b.Navigation("SubraceFeatures");
                });

            modelBuilder.Entity("WebClient.Models.Item", b =>
                {
                    b.Navigation("BackgroundItems");

                    b.Navigation("CharacterInventories");

                    b.Navigation("FirstItemSets");

                    b.Navigation("SecondItemSets");
                });

            modelBuilder.Entity("WebClient.Models.Lobby", b =>
                {
                    b.Navigation("UsersInLobby");
                });

            modelBuilder.Entity("WebClient.Models.Message", b =>
                {
                    b.Navigation("LobbyChats");

                    b.Navigation("PrivateMessages");
                });

            modelBuilder.Entity("WebClient.Models.Quest", b =>
                {
                    b.Navigation("QuestEvents");
                });

            modelBuilder.Entity("WebClient.Models.Race", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("RaceFeatures");

                    b.Navigation("Subraces");
                });

            modelBuilder.Entity("WebClient.Models.Skill", b =>
                {
                    b.Navigation("BackgroundSkills");

                    b.Navigation("ClassSkills");
                });

            modelBuilder.Entity("WebClient.Models.Subrace", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("SubraceFeatures");
                });

            modelBuilder.Entity("WebClient.Models.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("FriendOfUsers");

                    b.Navigation("HostedLobbies");

                    b.Navigation("Messages");

                    b.Navigation("PrivateMessagesReceived");

                    b.Navigation("UserCampaigns");

                    b.Navigation("UserCharacters");

                    b.Navigation("UserFriends");

                    b.Navigation("UsersInLobby");
                });

            modelBuilder.Entity("WebClient.Models.WeaponTag", b =>
                {
                    b.Navigation("WeaponTagWeapons");
                });

            modelBuilder.Entity("WebClient.Models.Weapon", b =>
                {
                    b.Navigation("WeaponTagWeapons");
                });
#pragma warning restore 612, 618
        }
    }
}
